// ================================================================
// TestCase Studio — Playwright Script
// Name  : Recorded_Test
// Date  : 9/11/2026, 3:31:34 PM
// Steps : 19
// ================================================================
// RUN:
//   npm install && npx playwright install chromium
//   node Recorded_Test.spec.js
// ================================================================
// LOCATOR STRATEGY per element step (tried in order):
//   1. Primary XPath (recorded)
//   2. Primary CSS   (recorded)
//   3. Index-based XPath   e.g. (//button)[4]
//   4. Text-based XPath    e.g. //button[normalize-space()="OK"]
//   5. Partial-ID XPath    e.g. //input[contains(@id,"field-")]
// ================================================================

'use strict';
const { chromium } = require('playwright');

// ─── findElement: tries every locator in order, first match wins ────────────
// Generated by TestCase Studio. Handles dynamic IDs automatically.
async function findElement(locators, stepDesc) {
  const errs = [];
  for (const { label, loc } of locators) {
    try {
      await loc.waitFor({ state: 'attached', timeout: 3000 });
      if (await loc.count() > 0) {
        process.stdout.write('  [✓] ' + stepDesc + ' → ' + label + '\n');
        return loc.first();
      }
      errs.push(label + ': 0 elements matched');
    } catch (e) {
      errs.push(label + ': ' + e.message.split('\n')[0]);
    }
  }
  throw new Error(
    'Element not found for: "' + stepDesc + '"\n' +
    errs.map((e, i) => '  ' + (i + 1) + '. ' + e).join('\n') + '\n' +
    'Tip: Re-record this step if the page structure changed.'
  );
}
// ─────────────────────────────────────────────────────────────────────────────

(async () => {
  const browser = await chromium.launch({ headless: false, slowMo: 80 });
  const context = await browser.newContext();
  const page    = await context.newPage();

  // ── 19 Recorded Steps ─────────────────────────────────────

  // Step 1: Open website
  await page.goto('https://accenture70.pegalabs.io/prweb/app/clmkyc--client-onboarding-for-financial-services-2/beEBp4uRVTogorRwSwWqbOtn9IL2fwdI*/!STANDARD?pzuiactionrrr=CXtpbn10LzZxdDFCemFBZXNpWGhsdU9URFJhNmIrc2pkL2Rjc3dTZllMM3JCYUoreGRoUUxYWmNhT24yVUdxK3dFQVA3MFZrcVJESnZkVmhrSjVuSVB3c1ZET0tkeXFvUEE3RGJ4akduRkJjVzNTbENna1owTjlIQnp1NkRrdXVFOXNRUUpiK1IxRUpVeDU3MFNzbnFoSW5vT1p6UkpVL2tUR1YySXhVNXZlM091aDg9*');

  // Step 2: Enter "abhinav.n.mishra@accenture.com" into "User name
                                            User name"
  // Playwright: page.locator('#txtUserID')
  const el_2 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'txtUserID\']') },
    { label: 'CSS (primary)', loc: page.locator('#txtUserID') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[1]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(1)') }
  ], 'Enter "abhinav.n.mishra@accenture.com" into "User name
                                            User name"');
  await el_2.fill(`abhinav.n.mishra@accenture.com`);

  // Step 3: Enter "******" into "Password
                                            Password"
  // Playwright: page.locator('#txtPassword')
  const el_3 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'txtPassword\']') },
    { label: 'CSS (primary)', loc: page.locator('#txtPassword') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[2]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(1)') }
  ], 'Enter "******" into "Password
                                            Password"');
  await el_3.fill(`******`);

  // Step 4: Click on "Log in"
  // Playwright: page.locator('#sub')
  const el_4 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[@id=\'sub\']') },
    { label: 'CSS (primary)', loc: page.locator('#sub') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[1]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//button[normalize-space()=\'Log in\']') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(1)') }
  ], 'Click on "Log in"');
  await el_4.click();

  // Step 5: Click on "Create"
  // Playwright: page.locator('body > app-root:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > nav:nth-child(3) > div:nth-child(1) > div:nth-child(1) > ul:nth-child(1) > li:nth-child(1) > button:nth-child(1) > div:nth-child(1) > span:nth-child(1) > svg:nth-child(1)')
  const el_5 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//div[@class=\'sc-fTrzCy kcoqE\']//*[@role=\'presentation\']') },
    { label: 'CSS (primary)', loc: page.locator('body > app-root:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > nav:nth-child(3) > div:nth-child(1) > div:nth-child(1) > ul:nth-child(1) > li:nth-child(1) > button:nth-child(1) > div:nth-child(1) > span:nth-child(1) > svg:nth-child(1)') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//svg)[4]') },
    { label: 'nth-of-type CSS', loc: page.locator('svg:nth-of-type(1)') }
  ], 'Click on "Create"');
  await el_5.click();

  // Step 6: Click on "Client Onboarding"
  // Playwright: page.locator('span')
  const el_6 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//span[normalize-space()=\'Client Onboarding\']') },
    { label: 'CSS (primary)', loc: page.locator('span') },
    { label: 'nth-of-type CSS', loc: page.locator('span:nth-of-type(1)') }
  ], 'Click on "Client Onboarding"');
  await el_6.click();

  // Step 7: Enter "client test" into "Client onboarding case name"
  // Playwright: page.locator('#_0o86y1cu7')
  const el_7 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'_0o86y1cu7\']') },
    { label: 'CSS (primary)', loc: page.locator('#_0o86y1cu7') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[2]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(1)') }
  ], 'Enter "client test" into "Client onboarding case name"');
  await el_7.fill(`client test`);

  // Step 8: select "Digital" from "Onboarding channel"
  // Playwright: page.locator('#_bw1wfsxef')
  const el_8 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//select[@id=\'_bw1wfsxef\']') },
    { label: 'CSS (primary)', loc: page.locator('#_bw1wfsxef') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//select)[1]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//select[normalize-space()=\'Select... Digital Branch Assisted\']') },
    { label: 'nth-of-type CSS', loc: page.locator('select:nth-of-type(1)') }
  ], 'select "Digital" from "Onboarding channel"');
  await el_8.selectOption({ label: `Digital` });

  // Step 9: Click on "abhinav.n.mishra@accenture.com"
  // Playwright: page.locator('body > div:nth-child(4) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > fieldset:nth-child(1) > ul:nth-child(1) > li:nth-child(1) > div:nth-child(2) > div:nth-child(2) > ul:nth-child(1) > li:nth-child(1)')
  const el_9 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//li[normalize-space()=\'abhinav.n.mishra@accenture.com\']') },
    { label: 'CSS (primary)', loc: page.locator('body > div:nth-child(4) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > fieldset:nth-child(1) > ul:nth-child(1) > li:nth-child(1) > div:nth-child(2) > div:nth-child(2) > ul:nth-child(1) > li:nth-child(1)') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//li)[18]') },
    { label: 'nth-of-type CSS', loc: page.locator('li:nth-of-type(1)') }
  ], 'Click on "abhinav.n.mishra@accenture.com"');
  await el_9.click();

  // Step 10: Click on "Client onboarding case nameOnboarding channelSelect...DigitalBranch AssistedInitiating userArrow dow"
  // Playwright: page.locator('.sc-fEXmlR.bPNMES.sc-jxfubC.lcXOYq.sc-fEXmlR.bPNMES')
  const el_10 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//div[@class=\'sc-fEXmlR bPNMES sc-jxfubC lcXOYq sc-fEXmlR bPNMES\']') },
    { label: 'CSS (primary)', loc: page.locator('.sc-fEXmlR.bPNMES.sc-jxfubC.lcXOYq.sc-fEXmlR.bPNMES') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//div)[63]') },
    { label: 'nth-of-type CSS', loc: page.locator('div:nth-of-type(1)') }
  ], 'Click on "Client onboarding case nameOnboarding channelSelect...DigitalBranch AssistedInitiating userArrow dow"');
  await el_10.click();

  // Step 11: Click on "Consent"
  // Playwright: page.locator('.sc-gkSfol.bniTBG.sc-fmPOXC.ibPDDS')
  const el_11 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//div[@class=\'sc-gkSfol bniTBG sc-fmPOXC ibPDDS\']') },
    { label: 'CSS (primary)', loc: page.locator('.sc-gkSfol.bniTBG.sc-fmPOXC.ibPDDS') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//div)[80]') },
    { label: 'nth-of-type CSS', loc: page.locator('div:nth-of-type(1)') }
  ], 'Click on "Consent"');
  await el_11.click();

  // Step 12: Click on "Close combobox list"
  // Playwright: page.locator('button[aria-label=\'Close combobox list\']')
  const el_12 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[@aria-label=\'Close combobox list\']') },
    { label: 'CSS (primary)', loc: page.locator('button[aria-label=\'Close combobox list\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[15]') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(1)') }
  ], 'Click on "Close combobox list"');
  await el_12.click();

  // Step 13: Click on "Kenji Nakamura"
  // Playwright: page.locator('body > div:nth-child(4) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > fieldset:nth-child(1) > ul:nth-child(1) > li:nth-child(3) > div:nth-child(2) > div:nth-child(1) > span:nth-child(1)')
  const el_13 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//span[normalize-space()=\'Kenji Nakamura\']') },
    { label: 'CSS (primary)', loc: page.locator('body > div:nth-child(4) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > fieldset:nth-child(1) > ul:nth-child(1) > li:nth-child(3) > div:nth-child(2) > div:nth-child(1) > span:nth-child(1)') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//span)[58]') },
    { label: 'nth-of-type CSS', loc: page.locator('span:nth-of-type(1)') }
  ], 'Click on "Kenji Nakamura"');
  await el_13.click();

  // Step 14: Click on "Client onboarding case nameOnboarding channelSelect...DigitalBranch AssistedInitiating userArrow dow"
  // Playwright: page.locator('.sc-fEXmlR.bPNMES.sc-jxfubC.lcXOYq.sc-fEXmlR.bPNMES')
  const el_14 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//div[@class=\'sc-fEXmlR bPNMES sc-jxfubC lcXOYq sc-fEXmlR bPNMES\']') },
    { label: 'CSS (primary)', loc: page.locator('.sc-fEXmlR.bPNMES.sc-jxfubC.lcXOYq.sc-fEXmlR.bPNMES') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//div)[63]') },
    { label: 'nth-of-type CSS', loc: page.locator('div:nth-of-type(1)') }
  ], 'Click on "Client onboarding case nameOnboarding channelSelect...DigitalBranch AssistedInitiating userArrow dow"');
  await el_14.click();

  // Step 15: Click on "Next"
  // Playwright: page.locator('body > div:nth-child(4) > div:nth-child(1) > div:nth-child(1) > footer:nth-child(3) > div:nth-child(2) > button:nth-child(2)')
  const el_15 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[@data-testid=\':assignment-action-buttons:submit\']') },
    { label: 'CSS (primary)', loc: page.locator('body > div:nth-child(4) > div:nth-child(1) > div:nth-child(1) > footer:nth-child(3) > div:nth-child(2) > button:nth-child(2)') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[18]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//button[normalize-space()=\'Next\']') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(2)') }
  ], 'Click on "Next"');
  await el_15.click();

  // Step 16: Click on "Submit"
  // Playwright: page.locator('body > div:nth-child(4) > div:nth-child(1) > div:nth-child(1) > footer:nth-child(3) > div:nth-child(2) > button:nth-child(3)')
  const el_16 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[@data-testid=\':assignment-action-buttons:submit\']') },
    { label: 'CSS (primary)', loc: page.locator('body > div:nth-child(4) > div:nth-child(1) > div:nth-child(1) > footer:nth-child(3) > div:nth-child(2) > button:nth-child(3)') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[18]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//button[normalize-space()=\'Submit\']') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(3)') }
  ], 'Click on "Submit"');
  await el_16.click();

  // Step 17: Click on "Go"
  // Playwright: page.locator('button[aria-label=\'Go - Enter Profile Details\']')
  const el_17 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[normalize-space()=\'Go\']') },
    { label: 'CSS (primary)', loc: page.locator('button[aria-label=\'Go - Enter Profile Details\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[33]') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(1)') }
  ], 'Click on "Go"');
  await el_17.click();

  // Step 18: Click on "_rbw3keuw0-field"
  // Playwright: page.locator('body > app-root:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > main:nth-child(4) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > article:nth-child(1) > div:nth-child(1) > article:nth-child(2) > div:nth-child(1) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > article:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(4) > div:nth-child(1) > span:nth-child(1) > div:nth-child(1) > div:nth-child(1) > label:nth-child(2) > div:nth-child(1)')
  const el_18 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//label[@for=\'_rbw3keuw0\']//div[@class=\'sc-gkSfol bniTBG sc-fmPOXC ibPDDS\']') },
    { label: 'CSS (primary)', loc: page.locator('body > app-root:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > main:nth-child(4) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > article:nth-child(1) > div:nth-child(1) > article:nth-child(2) > div:nth-child(1) > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > article:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(4) > div:nth-child(1) > span:nth-child(1) > div:nth-child(1) > div:nth-child(1) > label:nth-child(2) > div:nth-child(1)') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//div)[157]') },
    { label: 'nth-of-type CSS', loc: page.locator('div:nth-of-type(1)') }
  ], 'Click on "_rbw3keuw0-field"');
  await el_18.click();

  // Step 19: Click on "Submit"
  // Playwright: page.locator('body > app-root:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > main:nth-child(4) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > article:nth-child(1) > div:nth-child(1) > article:nth-child(2) > div:nth-child(1) > form:nth-child(1) > div:nth-child(2) > div:nth-child(2) > button:nth-child(3)')
  const el_19 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[@data-testid=\':assignment-action-buttons:submit\']') },
    { label: 'CSS (primary)', loc: page.locator('body > app-root:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > main:nth-child(4) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > article:nth-child(1) > div:nth-child(1) > article:nth-child(2) > div:nth-child(1) > form:nth-child(1) > div:nth-child(2) > div:nth-child(2) > button:nth-child(3)') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[44]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//button[normalize-space()=\'Submit\']') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(3)') }
  ], 'Click on "Submit"');
  await el_19.click();

  console.log('\n✓ All 19 steps passed.');
  await browser.close();
})().catch(err => {
  console.error('\n✗ Test failed:', err.message);
  process.exit(1);
});